name: Install Crystal
description: Install Crystal programming language
inputs:
  crystal:
    description: The version of Crystal to install ("latest", "nightly", "0.35.1" etc)
  shards:
    description: The version of Shards to install (true, "latest", "nightly", "0.13.0" etc)
  arch:
    description: The architecture of the build of Crystal ("x86_64")
  destination:
    description: The directory to store Crystal in
  annotate:
    description: Display compilation and spec errors as GitHub code annotations
  token:
    description: Personal access token (auto-populated)
    default: ${{ github.token }}
outputs:
  crystal:
    description: The actual version of Crystal that was installed
  shards:
    description: The actual version of Shards that was installed
  path:
    description: The directory where Crystal was installed
runs:
  using: node16
  main: index.js
branding:
  icon: octagon
  color: gray-dark
