import {defineConfig, globalIgnores} from "eslint/config";
import eslint from "@eslint/js";
import globals from "globals";
import stylistic from "@stylistic/eslint-plugin";

export default defineConfig([
    globalIgnores([
        "docs/",
        "site/",
    ]),
    stylistic.configs.customize({
        indent: 4,
        quotes: "double",
        semi: true,
        braceStyle: "1tbs",
    }),
    eslint.configs.recommended,
    {languageOptions: {
        sourceType: "module",
        parserOptions: {
            ecmaVersion: 2020,
        },
        globals: {
            ...globals.node,
        },
    }},
    {rules: {
        "@stylistic/array-bracket-spacing": "error",
        "@stylistic/arrow-parens": ["error", "always"],
        "@stylistic/arrow-spacing": "error",
        "@stylistic/brace-style": "error",
        "@stylistic/comma-dangle": ["error", "always-multiline"],
        "@stylistic/comma-spacing": "error",
        "@stylistic/comma-style": "error",
        "@stylistic/computed-property-spacing": "error",
        "@stylistic/eol-last": "error",
        "@stylistic/function-call-spacing": "error",
        "@stylistic/generator-star-spacing": ["error", "after"],
        "@stylistic/implicit-arrow-linebreak": "error",
        "@stylistic/key-spacing": "error",
        "@stylistic/keyword-spacing": "error",
        "@stylistic/no-confusing-arrow": "error",
        "@stylistic/no-extra-semi": "error",
        "@stylistic/no-multi-spaces": ["error"],
        "@stylistic/no-multiple-empty-lines": "error",
        "@stylistic/no-trailing-spaces": "error",
        "@stylistic/no-whitespace-before-property": "error",
        "@stylistic/object-curly-spacing": ["error", "never"],
        "@stylistic/padded-blocks": ["error", "never"],
        "@stylistic/quote-props": "off",
        "@stylistic/quotes": ["error", "double"],
        "@stylistic/rest-spread-spacing": "error",
        "@stylistic/semi": "error",
        "@stylistic/semi-spacing": "error",
        "@stylistic/semi-style": "error",
        "@stylistic/space-before-function-paren": ["error", {anonymous: "always", named: "never", asyncArrow: "always"}],
        "@stylistic/space-in-parens": ["error", "never"],
        "@stylistic/space-infix-ops": "error",
        "@stylistic/space-unary-ops": "error",
        "@stylistic/spaced-comment": ["error", "always", {markers: ["/"]}],
        "@stylistic/switch-colon-spacing": "error",
        "@stylistic/template-curly-spacing": "error",
        "@stylistic/template-tag-spacing": "error",
        "@stylistic/type-annotation-spacing": "error",
        "@stylistic/yield-star-spacing": "error",
        "arrow-body-style": ["error", "as-needed"],
        "block-scoped-var": "error",
        "camelcase": "error",
        "consistent-return": "error",
        "curly": ["error", "all"],
        "eqeqeq": ["error", "always", {"null": "ignore"}],
        "func-style": ["error", "declaration"],
        "max-len": ["error", {code: 120, ignoreStrings: true, ignoreTemplateLiterals: true}],
        "no-cond-assign": ["error", "except-parens"],
        "no-duplicate-imports": "error",
        "no-empty": ["error", {allowEmptyCatch: true}],
        "no-floating-decimal": "error",
        "no-implicit-globals": "error",
        "no-implied-eval": "error",
        "no-mixed-operators": "error",
        "no-multi-str": "error",
        "no-return-assign": "error",
        "no-return-await": "error",
        "no-self-compare": "error",
        "no-sequences": "error",
        "no-unneeded-ternary": "error",
        "no-unused-vars": ["error", {"caughtErrors": "none"}],
        "no-useless-return": "error",
        "no-var": "error",
        "operator-assignment": "error",
        "prefer-arrow-callback": "error",
        "prefer-const": ["error", {"destructuring": "all"}],
        "prefer-destructuring": "error",
        "prefer-numeric-literals": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "require-await": "error",
        "sort-imports": "error",
        "sort-keys": ["error", "asc", {minKeys: 10}],
        "unicode-bom": "error",
        "yoda": "error",
    }},
]);
