name: Deploy docs
on:
  push:
    paths: ['docs/**', '*.md']
  pull_request:
    paths: ['docs/**', '*.md']
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install -r docs/requirements.txt
      - name: Fetch branch
        run: git fetch origin v1:v1
      - name: Build site
        run: mkdocs build
        working-directory: docs
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: oprypin/push-to-gh-pages@v3
        with:
          publish_dir: site
          commit_message: 'Generate docs: '
