name: Test Action
on: workflow_dispatch
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: ./
        with:
          crystal: ${{ matrix.crystal }}
